"""Price column addition

Revision ID: 4d8c5fb49bee
Revises: 68ae0b7515b8
Create Date: 2025-12-05 11:06:11.421264

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8c5fb49bee'
down_revision: Union[str, Sequence[str], None] = '68ae0b7515b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('price', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_book_price'), 'book', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_price'), table_name='book')
    op.drop_column('book', 'price')
    # ### end Alembic commands ###
